name: Build and Publish test image to GHCR 🚀

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            architecture: amd64
          - runner: ubuntu-24.04-arm
            architecture: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker buildx build \
            --platform linux/${{ matrix.architecture }} \
            --cache-from=type=registry,ref=ghcr.io/ophelios-studio/docker-pulsar-php84-test:cache-${{ matrix.architecture }} \
            --cache-to=type=registry,ref=ghcr.io/ophelios-studio/docker-pulsar-php84-test:cache-${{ matrix.architecture }},mode=max \
            --tag ghcr.io/ophelios-studio/docker-pulsar-php84-test:${{ matrix.architecture }} \
            --load \
            .

      - name: Push image
        run: |
          docker push ghcr.io/ophelios-studio/docker-pulsar-php84-test:${{ matrix.architecture }}

  create-multiarch-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/ophelios-studio/docker-pulsar-php84-test:latest \
            --amend ghcr.io/ophelios-studio/docker-pulsar-php84-test:amd64 \
            --amend ghcr.io/ophelios-studio/docker-pulsar-php84-test:arm64

          docker manifest push ghcr.io/ophelios-studio/docker-pulsar-php84-test:latest
