name: Build and Publish image to GHCR 🚀

# For latest images, we want to build and publish the image when a push is made to the main branch
on:
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            architecture: amd64
          - runner: ubuntu-24.04-arm # Use an ARM runner to prevent QEMU emulation which is slow
            architecture: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/ophelios-studio/docker-pulsar-php84:cache-${{ matrix.architecture }}
          cache-to: type=registry,ref=ghcr.io/ophelios-studio/docker-pulsar-php84:cache-${{ matrix.architecture }},mode=max
          push: true
          tags: ghcr.io/ophelios-studio/docker-pulsar-php84:latest
          platforms: linux/amd64,linux/arm64
