name: CD - Dev 🚀

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/build-publish-docker.yml
    with:
      image_name: "docker-pulsar-php84-test"
      tag: "latest"
