name: CD - Prod 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/build-publish-docker.yml
    with:
      image_name: "docker-pulsar-php84"
      tag: "latest"
