name: Publish to ghcr

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64, amd64]

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ophelios-studio/docker-pulsar-php84:latest
          platforms: linux/${{ matrix.architecture }}
